---

- name: deploy to server
  hosts: localhost
  sudo: true
  vars_files:
    - vars/main.yml

  roles:
    #- common
    #- mysql
    #- keystone
    #- glance
    #- openvswitch
    #- neutron
    #- cinder
    #- nova
    - horizon
