---

#- name: add havana cloud archive
#  command: add-apt-repository cloud-archive:havana

#- name: update apt cache
#  apt: update_cache=yes

- name: install common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server 
    - python-mysqldb 
    - rabbitmq-server 
    - ntp

- name: enable ip forwarding
  command: sysctl net.ipv4.ip_forward=1

- name: make ip forwarding permanent
  lineinfile: dest=/etc/sysctl.conf
              regexp='^#net.ipv4.ip_forward=1'
              line='net.ipv4.ip_forward=1'
              backrefs=yes
